version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile  # 这里应该是你的 Dockerfile 的路径
    image: my-nginx-proxy-manager
    container_name: my-nginx-proxy-manager-container
    ports:
      - "80:80"
      - "443:443"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
